name: mobile_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.12.2
  shared_preferences: ^2.5.5
  image_picker: ^1.2.1
  speech_to_text: ^7.0.0
  intl: ^0.20.2
  flutter_stripe: ^10.1.1
  nfc_manager: ^4.1.1
  google_maps_flutter: ^2.17.0
  geolocator: ^14.0.2
  shimmer: ^3.0.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0
  mobile_scanner: ^6.0.0
  fl_chart: ^1.2.0
  share_plus: ^10.1.0
  gallery_saver_plus: ^3.2.9
  uuid: ^4.5.1
  pdf: ^3.12.0
  printing: ^5.14.3
  geocoding: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: '#ffffff'
  fullscreen: true